micronaut:
  application:
    name: r2dbcdemo
netty:
  default:
    allocator:
      max-order: 3

datasources:
  default:
    url: jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ""
    driverClassName: org.h2.Driver

r2dbc:
  datasources:
    default:
      driver: h2
      url: r2dbc:h2:mem:///default
      username: sa
      password: ""

flyway:
  datasources:
    default:
      enabled: true